iovisor/kubectl-trace

cmd/kubectl-trace/root.go
go.mod
go.sum

This allows `kubectl-trace` to talk to GKE clusters where the kubeconfig was provided by `gcloud container clusters get-credentials`.

feat(cmd): add support for gke auth provider

---

.travis.yml
Makefile
hack/release-image.sh

feat(ci): specific build branch name under travis

---

hack/ci-build-image.sh
hack/ci-release-image.sh

fix(kubectl-trace): image build trigger should not stay in makeopts

---

cmd/kubectl-trace/root.go
vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/OWNERS
vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
vendor/modules.txt

Symptoms:
```
kubectl trace run $NODE_NAME -e "tracepoint:syscalls:sys_enter_* { @[probe] = count(); }"
Error: No Auth Provider found for name "oidc"
```
The client/auth/oidc pkg in client-go is not vendored. This patch adds the blank import.
Signed-off-by: Alban Crequy <alban@kinvolk.io>

Add support for oidc auth on Kubernetes

---

Dockerfile.tracerunner
Makefile
pkg/version/version.go

I have been testing with the following:
```
export IMAGE_NAME=quay.io/alban/kubectl-trace-bpftrace
export IMAGE_NAME_BASE=quay.io/alban/kubectl-trace-bpftrace-base
```

fix(kubectl-trace): image name configurable

---

pkg/tracejob/job.go

Fixes #49 
This sets the trace job to be burstable, with a very low CPU requirement (1/10th of a CPU), to ensure that the job can be easily scheduled without being disruptive. It sets a maximum of 1 full CPU as well.
Similarly, for memory it requires 100mb, with a maximum of 1Gb.
We can tune these up or down as need be, but for now this should be a wide range to operate in.
If #47 is merged, then requests/limits should be applied to the initContainer as well.
@fntlnz what do you think?

fix: Specify resource requests and limits for trace job

---

Makefile
integration/suite_test.go
pkg/cmd/attach.go
pkg/cmd/delete.go
pkg/cmd/get.go
pkg/cmd/log.go
pkg/cmd/run.go
pkg/cmd/trace.go
pkg/cmd/tracerunner.go
pkg/cmd/version.go
pkg/tracejob/job.go
pkg/version/version.go

Closes #53 
Regards #48 too (probably needs to be rebased on top of this or the master if this will be merged, to continue to work on).
This PR introduces the following flags for the run command and behavior:
- `--imagename` (defaulting to "quay.io/fntlnz/kubectl-trace-bpftrace:latest")
- `--init-imagename` (defaulting to "quay.io/dalehamel/kubectl-trace-init")
- `--fetch-headers` (defaulting to false)
Notice that defaults will be changed when we'll have "official" default images.
Furthermore this PR removes from version command the info about the tracerunner image in use since it is not related to the version of kubectl-trace imho.

Images and headers flags for run command

---

pkg/logs/logs.go

Small change to accept pod in `Succeeded` phase.
Attempt to fix #61 
```shell
$ kubectl get pod kubectl-trace-43db844d-3ae6-11e9-8802-9cb6d0de1923-bkrwj 
NAME                                                       READY   STATUS      RESTARTS   AGE
kubectl-trace-43db844d-3ae6-11e9-8802-9cb6d0de1923-bkrwj   0/1     Completed   0          12m
```
```shell
$ kubectl trace log 43db844d-3ae6-11e9-8802-9cb6d0de1923
kubelet: /sys/fs/cgroup/blkio/kubepods/blkio.throttle.io_serviced
kubelet: /sys/fs/cgroup/memory/kubepods/memory.stat
redis-server: /proc/1/stat
^C
first SIGINT received, now if your program had maps and did not free them it should print them out
```
The output is displayed. 🙂

fix: Accept completed job for log command

---

pkg/cmd/get.go
pkg/tracejob/job.go
vendor/k8s.io/apimachinery/pkg/util/duration/duration.go
vendor/modules.txt

Add `Status` and `age` fields in the table printed out on a `kubectl trace get`
Attempt to fix #34
[![](https://user-images.githubusercontent.com/273896/53654156-078d6000-3c1b-11e9-86e1-4cee970d1f19.png)](https://github.com/iovisor/kubectl-trace/labels/good%20first%20issue)
```shell
$ kubectl trace get
NAMESPACE	NODE		NAME							STATUS		AGE	
default		kind-worker2	kubectl-trace-f2db30bc-3c3e-11e9-a337-9cb6d0de1923	Running		27s	
default		kind-worker1	kubectl-trace-f4dbd43e-3c3e-11e9-8c3c-9cb6d0de1923	Completed	24s	
```
Here we have two traces, one running and the other completed.
We can also add other fields such as `duration` but I am not sure that it is very useful.

feat: Implement missing fields in Get

---

Makefile
init/Dockerfile.initcontainer
init/fetch-linux-headers.sh
pkg/tracejob/job.go
pkg/version/version.go

This should be reasonably ready for review, and should fix #47 
As of now, the current status is:
* This works! I can run a test script on container OS now.
* It appears to be able to successfully download and generate headers to a shared location, and this is reasonably fast, subsequent loads don't have any noticeable overhead from the initContainer as I had hoped
* When headers are already installed, the initContainer exists almost immediately and the tracer can start
* Headers will be read unconditionally from a cached path at `/var/cache/linux-headers`, which should dependably be writeable (see https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s05.html). Since we are literally just caching the headers, this should be fine
* For hosts where headers are already installed, this will …

feat: Automatically fetch headers for Google's Container OS linux header install via initContainer

---

init/fetch-linux-headers.sh

@leodido @fntlnz please take a look
This should enhance the `--fetch-headers` code path to work for any linux distribution, not just container OS. 
I've also optimized a bit, by deleting abundant non-header files that aren't needed, which speeds up the inter-device move pretty substantially. I also decided it would be prudent to keep track of the time spent in the major operations in the script.
I've tested the generic path by commenting out the container OS one, but please try it for yourself to be sure it's all working as expected.

feat(init): support installing headers on generic linux distributions

---

Dockerfile.bpftracebase
Makefile

- Updated bpftrace to 81b099f094d2e6092cfe1317cbaaba0c1bbb614f
- Updated bcc to 0.8.0

chore(bpftracebase): bump bpftrace base to 81b099f094d2e6092cfe1317cbaaba0c1bbb614f and bcc 0.8.0

---

pkg/cmd/attach.go
pkg/cmd/delete.go
pkg/cmd/get.go

chore(pkg/cmd): add examples to attach

---

Dockerfile.bpftracebase

My original branch depended on an upstream change in bpftrace, but it's not needed. Providing `bpftrace` as a build target is enough.
Resolves #43.

fix: Don't build bpftrace tests

---

pkg/tracejob/job.go

Ensure that /usr/src is mounted, since several common distributions link
`/lib/modules/$(uname -r)/build` to `/usr/src/kernels/$(uname -r)` or
`/usr/src/linux-headers-$(uname -r)`.
This was required for me to successfully locate kernel headers on Amazon Linux 2.
Fixes: #76

fix: Mount /usr/src in pod template

---

build/init/fetch-linux-headers.sh

@leodido @fntlnz 
Updates the header fetching script to match the one we use internally, a few minor adjustments but should be functionally equivalent.

feat: Update linux header fetching script

---

.gitignore
.goreleaser.yml
.travis.yml
Makefile

This issue will setup goreleaser and cross compile kubectl-trace for multiple platforms. This would be a starting point for issue #9.

build: configure cross compile test builds

---

docs/release.md

docs: describe the release process

---

pkg/cmd/get.go
pkg/tracejob/job.go

In some cases, the job has no start time (`Job.Status.StartTime = nil`).
We keep the pointer values ​​and display `<unknown>` in the case of `nil` thanks to `timestamp.IsZero()`
```
func (t *Time) IsZero() bool {
if t == nil {
return true
}
return t.Time.IsZero()
}
```
Fixes: #87

fix: no job start time case

---

pkg/cmd/run.go
pkg/tracejob/job.go

Fixes #80 and paves the way for #11 
I think this is pretty elegant and I have to give the credit for both ideas to @jerr 
This allows for ensuring that bpftrace is signalled with SIGINT to dump its map before exiting.
Have tested this and it works more reliably than the interactive traces via TTY attach.
A nice benefit is you can now collect data for a pre-set interval before exiting 😂

feat: Job deadlines

---

README.md

This PR edits curl cmd in README to fix curl error in linux os.
Fixes #95

docs: fix curl cmd for Linux OS #95

---

pkg/cmd/trace.go

Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>

Set `out` and `err` writers to error out persistently

---

pkg/tracejob/job.go

We have a few nodes that we couldn't `kubectl trace` effectively because they were tainted to prevent arbitrary pods from being scheduled to them.
In this case, however, we are specifically requesting for a pod to be scheduled to that node, but the taint was leaving the pod hanging in `Pending` until we manually edited the trace pod to add this toleration.

fix: Add blanket "NoSchedule" toleration to trace pod

---

build/Dockerfile.tracerunner
pkg/tracejob/job.go

Ubuntu has `/usr/src` with the kernel headers but on Flatcar Container Linux, this directory does not exist and the kernel headers are located in `/lib/modules/$(uname -r)` directly.
Attempting to mount `/usr/src` from the host causes Docker to attempt to create that directory but this does not work when the host /usr is read-only.
This patch mounts the host `/usr` into the tracerunner `/usr-host` instead because `/usr` always exists. Then, a symlink redirects `/usr/src` to `/usr-host/src` when needed.
Signed-off-by: Alban Crequy <alban@kinvolk.io>
Fixes https://github.com/iovisor/kubectl-trace/issues/102

fix: avoid mounting /usr/src for underlying Linux distros without it

---

Makefile
build/Dockerfile.tracerunner

This moves the trace runner image to use bpftrace 0.9.4 using the static+glibc build approach I've been working on.
There is also a `latest` tag being pushed for quay.io/iovisor/bpftrace, which we might want to expose as an option as well (`eg, a flag like --latest`) so that daring users can run against bpftrace HEAD.
The resulting image is actually much smaller as it no longer needs to pull in a panoply of LLVM and Clang libraries - these are statically compiled in. The bpftrace binary is about 40MB, which is comparable to the alpine image kubectl-trace originally used.
We could aim to slim the image down further if we can find a dockerfile that includes pretty much just glibc for a base image

feat: Bump bpftrace to v0.9.4 using new bpftrace docker image

---

build/Dockerfile.initcontainer
build/init/fetch-linux-headers.sh
pkg/tracejob/job.go

* check /boot on host for kernel config in addition to /proc/config.gz
* improve kernel version splitting when downloading kernel sources
* use elfutils-dev instead of libelf-dev to support preparing headers with kernel version used by Amazon Linux
RPMs for kernel source/headers are available, somehow, but it seems
older versions are not kept around or are hard to track down.

feat: support Amazon Linux when fetching headers

---

build/init/fetch-linux-headers.sh

The version of kubernetes I am using runs on an Ubuntu 4.15.0-88-generic kernel
When using HEAD 
```
kubectl trace run  xxx.xxx.xxx.xxx -e 'kprobe:do_sys_open { printf("%s: %s\n", comm, str(arg1)) }' --imagename quay.io/iovisor/kubectl-trace-bpftrace:HEAD --init-imagename=quay.io/iovisor/kubectl-trace-init:HEAD --fetch-headers 
```
the init container failed with 
```
+ mkdir -p /linux-generic-4.15.0-88-generic
+ curl -sL https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.15.0.tar.gz
+ tar --strip-components=1 -xzf - -C /linux-generic-4.15.0-88-generic
tar: invalid magic
tar: short read
real	0m0.112s
```
Navigating to https://mirrors.edge.kernel.org/pub/linux/kernel/v4.x/linux-4.15.0.tar.gz returns a 404.
Looking in the redirected root folder …

fix: .0 version number in kernel sources

---

build/Dockerfile.initcontainer
build/init/fetch-linux-headers.sh

This combines the efforts in #110 and #111 .
I ran a basic probe against a GKE cluster:
```
$ kubectl trace run $POD --fetch-headers -e 'tracepoint:syscalls:sys_enter_openat { printf("%s %s\n", comm, str(args->filename)); }' -a
```
and got:
```
kconfig.h:5:10: fatal error: 'generated/autoconf.h' file not found"
```
With some testing I realized I needed the Google COS detection fixes in #111 with the `bison` and `flex` dependency fixes in #110 (without them I get a missing package error). This PR combines the fixes from both of those PRs, dropping the `linux-lts-dev` package addition in #111 since that is not needed in light of the finer-grained `bison` and `flex` deps.
**Modifications:**
- build: add flex and bison packages to init container
- fix: google container os detection …

fix: header generation issues on new GKE clusters

---

build/Dockerfile.initcontainer

An attempt to generate headers for kernel `5.4.15-1.el7.elrepo.x86_64` failed in scripts/extract-cert.c due to missing openssl-dev package.
Error:
```
...
- make ARCH=x86 prepare
scripts/extract-cert.c:21:25: fatal error: openssl/bio.h: No such file or directory
#include <openssl/bio.h>
^
compilation terminated.
```
Full init container log attached:
[init-container-fetch-headers.log](https://github.com/iovisor/kubectl-trace/files/4897175/init-container-fetch-headers.log)

fix: some kernels require openssl-dev to generate headers

---

build/Dockerfile.tracerunner

This is one step to be able to use kernel headers from `CONFIG_IKHEADERS` in Minikube.
Note that it is not enough to make kubectl-trace work on Minikube, see other tasks in https://github.com/iovisor/kubectl-trace/issues/120.

feat: add xz-utils in container image for CONFIG_IKHEADERS support

---

Makefile
build/Dockerfile.tracerunner

Do some housekeeping and upgrade image to use latest versions of the tools. This is setting things up in preparation for #125 .
I have tested the upgraded image locally but open to more thorough testing as might be suggested.

feat: Upgrade bpftrace and base image

---

.github/workflows/goreleaser.yml
.krew.yaml

This is an attempt to fix #119 
@rajatjindal does this look correct to you? We already had goreleaser being called in github actions (see makefile), so I think that if the bot works as expected, this should be able to grab the artifacts from the release that is published?
@leodido @fntlnz 
cc @zqureshi

feat: Set up automated releases via krew

---

.goreleaser.yml
Makefile
integration/suite_test.go
pkg/cmd/run.go

Successor to #130 but instead of changing things in code use linker flags for goreleaser.
This splits `ImageNameTag` into `ImageName` and `ImageTag` so that `ImageTag` can be overridden independently from `.goreleaser.yml`. Similarly for `InitImageNameTag`.
This change is fully backwards compatible and both the `--imagename` and `--init-imagename` flags work as expected.
Fixes #129 
@dalehamel @fntlnz @leodido

feat: Pin tagged release to container with same SHA

---

pkg/attacher/attach.go

Fixes #84 
When you do `kubectl trace run --attach` the job will have been created by `TraceJobClient` but the pod is not guaranteed to have been scheduled on any node. Therefore we cannot error out if no pod is found and must continue retrying.
It is easy to reproduce if you put a `panic()` in that area and I seem to hit it about 20% of my runs.
I also made it so that all errors encountered by the attacher are logged because they were silent right now and you wouldn't know that you attached to a blank `bpftrace` screen or attach failed and the local process is just waiting for a Ctrl-C.
@dalehamel @fntlnz

fix: Race condition in attacher looking for pod

---

README.md
go.mod
pkg/cmd/run.go
pkg/tracejob/job.go
pkg/tracejob/job_test.go
vendor/modules.txt

I ran into an issue where I needed the ability to alter the job spec for clusters with resource constraints (reducing cpu usage 
to 0.5 core), or where a specific resource request/limit ratio is enforced.
Rather than add multiple command line flags for each of these properties, I added a feature to allow an operator to apply a patch to the job spec immediately before `t.JobClient.Create(job)` is called. Patches can be written in either YAML or JSON using one of 3 merge strategies: `json`, `merge`, `strategic`.
For example, to customize the resource limits, you can create `limits.json` with the contents:
```json
[
{
"op": "replace",
"path": "/spec/template/spec/containers/0/resources",
"value": {
"limits": {
"cpu": "0.5",
"memory": "100Mi"
},
"requests": {
"cpu": "0.5",
"memory": "100Mi"
} …
```

feat: Allow patches to be applied to the job spec

---

build/Dockerfile.tracerunner

The current `bpftrace` version doesn't support the syntax of most `*.bt` programs of the bpftrace main repository.
Example of errors :
```bash
$ k logs -f kubectl-trace-efadffc7-28b8-4b22-be68-31e19f712a5d-8kzvv
if your program has maps to print, send a SIGINT using Ctrl-C, if you want to interrupt the execution send SIGINT two times
/programs/program.bt:25:34-37: ERROR: syntax error, unexpected identifier, expecting ) or ","
printf("%-10u %-5d ", elapsed / 1e6, pid);
~~~
exit status 1
```
As stated in [this issue](https://github.com/iovisor/bpftrace/issues/1686), upgrading to a more recent version fixes those syntax errors.

feat: upgrade bpftrace to latest version (fixing syntax errors).

---

.goreleaser.yml

Currently goreleaser omits the "v" from the tag name, which breaks the krew release. This attempts to resolve the issue.

fix: use goreleaser name template to match krew name format

---

.github/workflows/build-and-test.yml
Makefile
build/Dockerfile.tracerunner
build/hooks/prestop
go.mod
go.sum
integration/cmd_run_test.go
integration/kind_backend.go
integration/minikube_backend.go
integration/suite_test.go
pkg/cmd/tracerunner.go
pkg/docker/docker.go
pkg/docker/docker_test.go

This enhances the integration test suite in a variety of ways:
- Both minikube and KiND are now supported, and run in github actions
- Tests run in their own namespace, which is intelligently cleaned up
- Images are uploaded to a test backend via docker registry API
- Buildkit is used to significantly speed up incremental image builds
- The build time is cut almost in half in CI, as it is much faster to push a docker image than copy a tarball
This commit also fixes a bug where failed jobs would not report their failure.
Co-authored-by: Aaron Olson <934893+honkfestival@users.noreply.github.com>
Co-authored-by: Zeeshan Qureshi <zee@zqureshi.in>

feat: Integration test enhancements

---

build/Dockerfile.tracerunner
build/test/fake/success
go.mod
go.sum
integration/cmd_run_test.go
pkg/cmd/get.go
pkg/cmd/run.go
pkg/cmd/tracerunner.go
pkg/errors/errors.go
pkg/procfs/procfs.go
pkg/procfs/procfs_test.go
pkg/tracejob/job.go
pkg/tracejob/selected_target.go

This adds support for generic tracers, fixing #125
The new "--tracer" flag allows specifying arbitrary generic tracers.
The bcc suite of tools is added to take advantage of this, as well as a "fake"
tracer for integration testing this functionality, fixing #112
The primary original author of this functionality was Zeeshan Qureshi.
In order to pull this change in, it was necessary to also pull in functionality
that refactored how trace job targets are specified. This introduces a new flag
which allows specifying the target namespace separately from the namespace
where the trace is created, which fixes #147. This functionality was co-authored
with Aaron Olson.
Co-authored-by: Aaron Olson <934893+honkfestival@users.noreply.github.com>
Co-authored-by: Zeeshan Qureshi <zee@zqureshi.in>

feat: Support generic tracers, bcc, target namespace

---

Makefile
build/Dockerfile.tracerunner
build/test/fake/pidtrace
build/test/ruby/Dockerfile
build/test/ruby/Makefile
build/test/ruby/fork-from-args
integration/cmd_run_test.go
integration/suite_test.go
pkg/cmd/run.go
pkg/cmd/tracerunner.go
pkg/tracejob/job.go
pkg/tracejob/process_selector.go
pkg/tracejob/process_selector_test.go

This adds the ability to target a specific process to trace with the new flag
`--process-selector`. The prior behavior was that only the root PID of a pod
would be traced, which tends to not be the desired target process in most
cases.
Especially with the addition of generic tracers which may only work when a
target pid is provided, the ability to have more fine-grained control over what
process within a pod is targeted is desirable.
The selected process is substituted for `$container_pid` to preserve
backward-compatibility.
The primary author of this functionality was Aaron Olson, but it built on
earlier work from Zeeshan Qureshi who implemented the preliminary selector
work.
Co-authored-by: Aaron Olson <934893+honkfestival@users.noreply.github.com>
Co-authored-by: Zeeshan Qureshi …

feat: Support selecting target process to trace with "process selector"

---

.github/workflows/build-and-test.yml
build/Dockerfile.tracerunner
integration/cmd_run_test.go
pkg/cmd/run.go
pkg/cmd/tracerunner.go

This adds rbspy as a supported tracer, the first non-bpf based tracer, for
profiling Ruby processes.
This also adds support for post-processing with tracers, and takes advantage
of this to generate both speedscope and flamegraph output for rbspy.

feat: Add rbspy as a supported tracer, support post-processing

---

README.md
docs/secrets.md
docs/tracers.md

This adds documentation for generic tracers, including what criteria should be
used for including them in the project.
A missing document for how to work with secrets for uploading to blob storage
is also added.
An obsolete section of the README is also removed.

docs: Tracer and secrets docs

---

.github/workflows/build-and-test.yml

This ensures that the github actions workflow will push the latest image
when we merge to master.
This should fix part of #169

fix: Fix github actions workflow to push latest image

---

build/Dockerfile.initcontainer
build/init/fetch-linux-headers.sh

This PR updates the Alpine version in the init image to match the trace runner (3.15) to fix an outdated root certificate, adds several dependencies needed for newer kernel builds, and fixes a minor bug in the install script.
Attempting to run with `--fetch-headers` didn't actually fetch headers. Init container logs show:
```
+ curl -sL https://www.kernel.org/pub/linux/kernel/v5.x/linux-5.14.16.tar.gz
+ tar --strip-components=1 -xzf - -C /linux-generic-5.14.16-arch1-1
tar: invalid magic
tar: short read
```
Running the same curl command manually within the container indicated a certificate was expired. Adding OpenSSL clarified that this was due to the old LetsEncrypt [DST root's](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/) presence in the chain:
```
/ # openssl …
```

Update init image version and dependencies

---

.goreleaser.yml
.krew.yaml

Adds new build parameters for the arm64 arch for macOS and linux. Windows may also be addable this way but is not done here.
Fixes #178

build: Update build and release to produce arm64

---

build/init/fetch-linux-headers.sh

`tar` can't seem to read what is being passed to it without this,
see https://github.com/jupyterhub/mybinder.org-deploy/pull/2171#issuecomment-1132838971
for the error message.

Add -S to curl command when fetching generic headers

---

.github/workflows/build-and-test.yml

- ubuntu 16.04 was removed (https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/)
- let's test with ubuntu-latest as well
Signed-off-by: Lorenzo Fontana <fontanalorenz@gmail.com>

update(.github): build workflow runners

---

.github/workflows/build-and-test.yml
.github/workflows/goreleaser.yml

It looks like goreleaser changed the way they distribute packages and that affects our CI.
E.g: https://github.com/iovisor/kubectl-trace/runs/7639883360?check_suite_focus=true

fix(.github): goreleaser links not working

---

pkg/tracejob/job.go

This PR makes a `usr-host` Volume be conditionally added, side by side with the conditionally added VolumeMount entry referencing it.
I think the current behavior of declaring a volume that isn't mounted will be fully functional, and this fix just makes it easier to understand the workload by not including an unused volume.

refactor: only define usr-host volume if to be mounted by a container

---

pkg/cmd/get.go

This PR intends to fix an edge case of the `get` subcommand output.
When running on a (Kops) self-hosted cluster, the output of the get command looks like the following:
```bash
NAMESPACE	NODE					NAME							STATUS	AGE
agad-eu		ip-7-0-0-14.eu-east-1.compute.internalkubectl-trace-a3ffa902-ba04-11eb-8e15-acde48001122	Running	7s
agad-eu		ip-7-0-0-14.eu-east-1.compute.internalkubectl-trace-d7f161ea-b9c0-11eb-929a-acde48001122	Failed	8h
```
The following fix produces this output instead:
```bash
NAMESPACE        NODE                                            NAME                                                    STATUS          AGE
agad-eu          ip-7-0-0-14.eu-east-1.compute.internal          kubectl-trace-a3ffa902-ba04-11eb-8e15-acde48001122      Running         7s
agad-eu …
```

fix: Format get cmd output.

---

pkg/cmd/run.go

The logic of validation is wrong. If fileDefined, we should check the length of filename not program.

kubectl trace run validate logic

---

build/Dockerfile.initcontainer
build/init/fetch-linux-headers.sh

Without this, busybox's `diff` is used and I get the following message about 
it not supporting `-I`:
```
+ make ARCH=x86 prepare
diff: unrecognized option: I
BusyBox v1.34.1 (2022-04-04 10:19:27 UTC) multi-call binary.
Usage: diff [-abBdiNqrTstw] [-L LABEL] [-S FILE] [-U LINES] FILE1 FILE2
Compare files line by line and output the differences between them.
This implementation supports unified diffs only.
-a      Treat all files as text
-b      Ignore changes in the amount of whitespace
-B      Ignore changes whose lines are all blank
-d      Try hard to find a smaller set of changes
-i      Ignore case differences
-L      Use LABEL instead of the filename in the unified header
-N      Treat absent files as empty
-q      Output only whether files differ
-r      Recurse
--no-dereference …
```

Add diffutils to the trace initcontainer

---

.github/workflows/build-and-test.yml
.github/workflows/goreleaser.yml
Makefile

This fixes `goreleaser` not being found during the `make cross` step of the Build and Test workflow, as seen here:
> /bin/bash: goreleaser: command not found
https://github.com/iovisor/kubectl-trace/actions/runs/9952012009/job/27492540456#step:10:283
It would have been sufficient to add $GOPATH/bin to the PATH, but instead I use a `setup-go` step to be consistent with the release workflow, which takes care of this.
Additionally,
- it replaces the [deprecated --rm-dist goreleaser flag](https://goreleaser.com/deprecations/#-rm-dist) with `--clean` which I spotted while testing
- it bumps the go version in the release workflow to at 1.19 or higher in order to follow the `go.mod` file.

ci: fix goreleaser not being found
